import type {
  JobNotification,
  Application,
  Faculty,
  LeaveRequest,
  SalarySlip,
  Department,
  Education,
  ResearchPaper,
  Dependent,
  Announcement,
  AuditLog,
  PayrollRecord,
  Employee,
} from "./types"

export const mockJobs: JobNotification[] = [
  {
    id: "1",
    title: "Assistant Professor - Computer Science",
    department: "Computer Science",
    postType: "Assistant Professor",
    deadline: "2026-02-15",
    pdfUrl: "#",
    status: "active",
    createdAt: "2026-01-01",
  },
  {
    id: "2",
    title: "Associate Professor - Physics",
    department: "Physics",
    postType: "Associate Professor",
    deadline: "2026-02-20",
    pdfUrl: "#",
    status: "active",
    createdAt: "2026-01-05",
  },
  {
    id: "3",
    title: "Professor - Mathematics",
    department: "Mathematics",
    postType: "Professor",
    deadline: "2026-02-28",
    pdfUrl: "#",
    status: "active",
    createdAt: "2026-01-08",
  },
  {
    id: "4",
    title: "Assistant Professor - Chemistry",
    department: "Chemistry",
    postType: "Assistant Professor",
    deadline: "2026-03-01",
    pdfUrl: "#",
    status: "active",
    createdAt: "2026-01-10",
  },
  {
    id: "5",
    title: "Associate Professor - English",
    department: "English",
    postType: "Associate Professor",
    deadline: "2026-01-10",
    pdfUrl: "#",
    status: "closed",
    createdAt: "2025-12-15",
  },
]

export const mockDepartments: Department[] = [
  { id: "1", name: "Computer Science", code: "CS" },
  { id: "2", name: "Physics", code: "PHY" },
  { id: "3", name: "Mathematics", code: "MATH" },
  { id: "4", name: "Chemistry", code: "CHEM" },
  { id: "5", name: "English", code: "ENG" },
  { id: "6", name: "Economics", code: "ECO" },
]

export const mockEducation: Education[] = [
  { id: "1", degree: "10th", boardUniversity: "CBSE", year: "2010", percentage: "92", subject: "General" },
  { id: "2", degree: "12th", boardUniversity: "CBSE", year: "2012", percentage: "89", subject: "Science" },
  {
    id: "3",
    degree: "B.Tech",
    boardUniversity: "IIT Delhi",
    year: "2016",
    percentage: "8.5 CGPA",
    subject: "Computer Science",
  },
  {
    id: "4",
    degree: "M.Tech",
    boardUniversity: "IIT Bombay",
    year: "2018",
    percentage: "9.2 CGPA",
    subject: "Computer Science",
  },
  {
    id: "5",
    degree: "Ph.D",
    boardUniversity: "IISc Bangalore",
    year: "2023",
    percentage: "-",
    subject: "Machine Learning",
  },
]

export const mockResearchPapers: ResearchPaper[] = [
  {
    id: "1",
    title: "Deep Learning for Image Recognition",
    journalName: "IEEE Transactions",
    issn: "1234-5678",
    impactFactor: "4.5",
    year: "2022",
    authors: "John Doe, Jane Smith",
  },
  {
    id: "2",
    title: "Natural Language Processing Advances",
    journalName: "ACM Computing Surveys",
    issn: "2345-6789",
    impactFactor: "5.2",
    year: "2023",
    authors: "John Doe",
  },
]

export const mockApplications: Application[] = [
  {
    id: "APP001",
    jobId: "1",
    applicantId: "APL001",
    personalInfo: {
      fullName: "Rajesh Kumar",
      fatherName: "Suresh Kumar",
      dob: "1990-05-15",
      gender: "male",
      category: "General",
      nationality: "Indian",
      phone: "9876543210",
      email: "rajesh.kumar@email.com",
      address: "123 Main Street",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110001",
    },
    education: mockEducation,
    research: mockResearchPapers,
    documents: {
      photo: "/passport-photo.jpg",
      signature: "/handwritten-signature.png",
      cv: "resume.pdf",
    },
    apiScore: 85,
    status: "submitted",
    paymentStatus: "completed",
    submittedAt: "2026-01-10",
  },
  {
    id: "APP002",
    jobId: "1",
    applicantId: "APL002",
    personalInfo: {
      fullName: "Priya Sharma",
      fatherName: "Anil Sharma",
      dob: "1992-08-22",
      gender: "female",
      category: "OBC",
      nationality: "Indian",
      phone: "9876543211",
      email: "priya.sharma@email.com",
      address: "456 Park Avenue",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400001",
    },
    education: mockEducation.slice(0, 4),
    research: mockResearchPapers.slice(0, 1),
    documents: {
      photo: "/woman-passport-photo.jpg",
      signature: "/handwritten-signature.png",
      cv: "resume.pdf",
    },
    apiScore: 72,
    status: "under-review",
    paymentStatus: "completed",
    submittedAt: "2026-01-11",
  },
  {
    id: "APP003",
    jobId: "1",
    applicantId: "APL003",
    personalInfo: {
      fullName: "Amit Verma",
      fatherName: "Rakesh Verma",
      dob: "1988-12-03",
      gender: "male",
      category: "SC",
      nationality: "Indian",
      phone: "9876543212",
      email: "amit.verma@email.com",
      address: "789 Lake View",
      city: "Bangalore",
      state: "Karnataka",
      pincode: "560001",
    },
    education: mockEducation,
    research: [...mockResearchPapers, ...mockResearchPapers],
    documents: {
      photo: "/man-passport-photo-professional.jpg",
      signature: "/signature-handwriting.jpg",
      cv: "resume.pdf",
    },
    apiScore: 92,
    status: "shortlisted",
    paymentStatus: "completed",
    submittedAt: "2026-01-09",
  },
]

export const mockFaculty: Faculty = {
  id: "FAC001",
  employeeId: "EMP2020001",
  name: "Dr. Anand Mishra",
  email: "anand.mishra@university.edu",
  department: "Computer Science",
  designation: "Associate Professor",
  joiningDate: "2020-07-15",
  leaveBalance: {
    casual: 8,
    medical: 10,
    earned: 15,
  },
}

export const mockDependents: Dependent[] = [
  { id: "1", name: "Sunita Mishra", relation: "Spouse", dob: "1988-03-20", isDependent: true },
  { id: "2", name: "Rahul Mishra", relation: "Son", dob: "2015-08-10", isDependent: true },
  { id: "3", name: "Meera Mishra", relation: "Daughter", dob: "2018-12-05", isDependent: true },
]

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: "LR001",
    facultyId: "FAC001",
    facultyName: "Dr. Anand Mishra",
    leaveType: "casual",
    fromDate: "2026-01-15",
    toDate: "2026-01-16",
    reason: "Personal work",
    status: "approved",
    appliedAt: "2026-01-10",
  },
  {
    id: "LR002",
    facultyId: "FAC001",
    facultyName: "Dr. Anand Mishra",
    leaveType: "medical",
    fromDate: "2026-01-20",
    toDate: "2026-01-22",
    reason: "Medical checkup and rest",
    status: "pending",
    appliedAt: "2026-01-12",
  },
  {
    id: "LR003",
    facultyId: "FAC002",
    facultyName: "Dr. Priya Singh",
    leaveType: "earned",
    fromDate: "2026-02-01",
    toDate: "2026-02-10",
    reason: "Family vacation",
    status: "pending",
    appliedAt: "2026-01-11",
  },
  {
    id: "LR004",
    facultyId: "FAC003",
    facultyName: "Dr. Rakesh Gupta",
    leaveType: "casual",
    fromDate: "2026-01-18",
    toDate: "2026-01-18",
    reason: "Personal emergency",
    status: "rejected",
    remarks: "Insufficient leave balance",
    appliedAt: "2026-01-08",
  },
]

export const mockSalarySlips: SalarySlip[] = [
  {
    month: "January",
    year: 2026,
    earnings: { basic: 75000, da: 15000, hra: 18000, other: 5000 },
    deductions: { pf: 9000, tax: 8500, other: 1000 },
    netPay: 94500,
  },
  {
    month: "December",
    year: 2025,
    earnings: { basic: 75000, da: 15000, hra: 18000, other: 5000 },
    deductions: { pf: 9000, tax: 8500, other: 1000 },
    netPay: 94500,
  },
  {
    month: "November",
    year: 2025,
    earnings: { basic: 75000, da: 15000, hra: 18000, other: 5000 },
    deductions: { pf: 9000, tax: 8500, other: 1000 },
    netPay: 94500,
  },
  {
    month: "October",
    year: 2025,
    earnings: { basic: 75000, da: 15000, hra: 18000, other: 5000 },
    deductions: { pf: 9000, tax: 8500, other: 1000 },
    netPay: 94500,
  },
]

export const mockNotices = [
  {
    id: "1",
    title: "Annual Faculty Meeting",
    date: "2026-01-20",
    content: "All faculty members are requested to attend the annual meeting.",
  },
  {
    id: "2",
    title: "Research Grant Applications",
    date: "2026-01-18",
    content: "Last date for submitting research grant applications is Feb 15, 2026.",
  },
  {
    id: "3",
    title: "Holiday Notice",
    date: "2026-01-15",
    content: "University will remain closed on Jan 26, 2026 for Republic Day.",
  },
  {
    id: "4",
    title: "Semester End Examinations",
    date: "2026-01-12",
    content: "End semester examinations will commence from Feb 20, 2026.",
  },
]

export const mockAnnouncements: Announcement[] = [
  {
    id: "1",
    title: "New Recruitment Drive 2026",
    content:
      "We are excited to announce a new recruitment drive for multiple faculty positions across all departments. Applications are now open.",
    targetAudience: "all" as const,
    priority: "important" as const,
    publishedAt: "2026-01-10",
    expiresAt: "2026-03-01",
    isActive: true,
  },
  {
    id: "2",
    title: "Faculty Performance Review",
    content:
      "Annual performance reviews will be conducted from February 15-28. Please ensure all documentation is submitted.",
    targetAudience: "faculty" as const,
    priority: "urgent" as const,
    publishedAt: "2026-01-08",
    expiresAt: "2026-02-28",
    isActive: true,
  },
  {
    id: "3",
    title: "Application Portal Maintenance",
    content: "The application portal will undergo scheduled maintenance on January 25th from 2:00 AM to 6:00 AM IST.",
    targetAudience: "applicants" as const,
    priority: "normal" as const,
    publishedAt: "2026-01-12",
    expiresAt: "2026-01-26",
    isActive: true,
  },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: "1",
    userId: "ADM001",
    userName: "Admin User",
    action: "CREATE",
    module: "Recruitment",
    details: "Created new job posting: Assistant Professor - Computer Science",
    ipAddress: "192.168.1.100",
    timestamp: "2026-01-12T10:30:00",
  },
  {
    id: "2",
    userId: "ADM001",
    userName: "Admin User",
    action: "UPDATE",
    module: "Leave Approval",
    details: "Approved leave request LR001 for Dr. Anand Mishra",
    ipAddress: "192.168.1.100",
    timestamp: "2026-01-12T09:15:00",
  },
  {
    id: "3",
    userId: "ADM002",
    userName: "HR Manager",
    action: "UPDATE",
    module: "Employee",
    details: "Updated employee profile: Dr. Priya Singh (EMP2021002)",
    ipAddress: "192.168.1.105",
    timestamp: "2026-01-11T16:45:00",
  },
  {
    id: "4",
    userId: "ADM001",
    userName: "Admin User",
    action: "DELETE",
    module: "Settings",
    details: "Deleted department: History (HIS)",
    ipAddress: "192.168.1.100",
    timestamp: "2026-01-11T14:20:00",
  },
  {
    id: "5",
    userId: "ADM002",
    userName: "HR Manager",
    action: "CREATE",
    module: "Payroll",
    details: "Generated payroll for January 2026",
    ipAddress: "192.168.1.105",
    timestamp: "2026-01-10T11:00:00",
  },
  {
    id: "6",
    userId: "ADM001",
    userName: "Admin User",
    action: "UPDATE",
    module: "Scrutiny",
    details: "Marked application APP003 as shortlisted",
    ipAddress: "192.168.1.100",
    timestamp: "2026-01-09T15:30:00",
  },
]

export const mockPayrollRecords: PayrollRecord[] = [
  {
    id: "PR001",
    employeeId: "EMP2020001",
    employeeName: "Dr. Anand Mishra",
    department: "Computer Science",
    designation: "Associate Professor",
    month: "January",
    year: 2026,
    basic: 75000,
    da: 15000,
    hra: 18000,
    otherAllowances: 5000,
    pf: 9000,
    tax: 8500,
    otherDeductions: 1000,
    grossPay: 113000,
    netPay: 94500,
    status: "paid" as const,
    processedAt: "2026-01-05",
  },
  {
    id: "PR002",
    employeeId: "EMP2021002",
    employeeName: "Dr. Priya Singh",
    department: "Physics",
    designation: "Assistant Professor",
    month: "January",
    year: 2026,
    basic: 65000,
    da: 13000,
    hra: 15600,
    otherAllowances: 4000,
    pf: 7800,
    tax: 6500,
    otherDeductions: 800,
    grossPay: 97600,
    netPay: 82500,
    status: "paid" as const,
    processedAt: "2026-01-05",
  },
  {
    id: "PR003",
    employeeId: "EMP2019003",
    employeeName: "Dr. Rakesh Gupta",
    department: "Mathematics",
    designation: "Professor",
    month: "January",
    year: 2026,
    basic: 95000,
    da: 19000,
    hra: 22800,
    otherAllowances: 8000,
    pf: 11400,
    tax: 15000,
    otherDeductions: 1500,
    grossPay: 144800,
    netPay: 116900,
    status: "paid" as const,
    processedAt: "2026-01-05",
  },
  {
    id: "PR004",
    employeeId: "EMP2022004",
    employeeName: "Dr. Neha Sharma",
    department: "Chemistry",
    designation: "Assistant Professor",
    month: "January",
    year: 2026,
    basic: 60000,
    da: 12000,
    hra: 14400,
    otherAllowances: 3500,
    pf: 7200,
    tax: 5500,
    otherDeductions: 700,
    grossPay: 89900,
    netPay: 76500,
    status: "pending" as const,
    processedAt: undefined,
  },
]

export const mockEmployees: Employee[] = [
  {
    id: "FAC001",
    employeeId: "EMP2020001",
    name: "Dr. Anand Mishra",
    email: "anand.mishra@university.edu",
    phone: "9876543210",
    department: "Computer Science",
    designation: "Associate Professor",
    joiningDate: "2020-07-15",
    dateOfBirth: "1985-03-12",
    gender: "male" as const,
    address: "123 Faculty Housing, University Campus",
    qualification: "Ph.D in Computer Science",
    specialization: "Machine Learning, AI",
    status: "active" as const,
    bankAccount: "XXXX-XXXX-1234",
    panNumber: "ABCDE1234F",
    leaveBalance: {
      casual: 8,
      medical: 10,
      earned: 15,
    },
  },
  {
    id: "FAC002",
    employeeId: "EMP2021002",
    name: "Dr. Priya Singh",
    email: "priya.singh@university.edu",
    phone: "9876543211",
    department: "Physics",
    designation: "Assistant Professor",
    joiningDate: "2021-08-10",
    dateOfBirth: "1990-07-22",
    gender: "female" as const,
    address: "45 Staff Quarters, University Campus",
    qualification: "Ph.D in Physics",
    specialization: "Quantum Mechanics, Optics",
    status: "active" as const,
    bankAccount: "XXXX-XXXX-5678",
    panNumber: "FGHIJ5678K",
    leaveBalance: {
      casual: 10,
      medical: 12,
      earned: 8,
    },
  },
  {
    id: "FAC003",
    employeeId: "EMP2019003",
    name: "Dr. Rakesh Gupta",
    email: "rakesh.gupta@university.edu",
    phone: "9876543212",
    department: "Mathematics",
    designation: "Professor",
    joiningDate: "2019-07-01",
    dateOfBirth: "1975-11-05",
    gender: "male" as const,
    address: "78 Senior Faculty Block, University Campus",
    qualification: "Ph.D in Mathematics",
    specialization: "Number Theory, Algebra",
    status: "active" as const,
    bankAccount: "XXXX-XXXX-9012",
    panNumber: "KLMNO9012P",
    leaveBalance: {
      casual: 5,
      medical: 12,
      earned: 20,
    },
  },
  {
    id: "FAC004",
    employeeId: "EMP2022004",
    name: "Dr. Neha Sharma",
    email: "neha.sharma@university.edu",
    phone: "9876543213",
    department: "Chemistry",
    designation: "Assistant Professor",
    joiningDate: "2022-07-15",
    dateOfBirth: "1992-04-18",
    gender: "female" as const,
    address: "32 New Faculty Housing, University Campus",
    qualification: "Ph.D in Chemistry",
    specialization: "Organic Chemistry, Biochemistry",
    status: "active" as const,
    bankAccount: "XXXX-XXXX-3456",
    panNumber: "PQRST3456U",
    leaveBalance: {
      casual: 12,
      medical: 12,
      earned: 5,
    },
  },
  {
    id: "FAC005",
    employeeId: "EMP2018005",
    name: "Dr. Vikram Patel",
    email: "vikram.patel@university.edu",
    phone: "9876543214",
    department: "Economics",
    designation: "Professor",
    joiningDate: "2018-01-10",
    dateOfBirth: "1972-09-30",
    gender: "male" as const,
    address: "Senior Residence Block A, University Campus",
    qualification: "Ph.D in Economics",
    specialization: "Macroeconomics, Development Economics",
    status: "on-leave" as const,
    bankAccount: "XXXX-XXXX-7890",
    panNumber: "UVWXY7890Z",
    leaveBalance: {
      casual: 0,
      medical: 8,
      earned: 25,
    },
  },
]
